"""Fixed user_progress reference in Level model

Revision ID: 0252a628666f
Revises: 404d39ac6320
Create Date: 2025-02-25 02:15:23.421642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0252a628666f'
down_revision = '404d39ac6320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_level_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('best_score', sa.Float(), nullable=True))
        batch_op.drop_index('ix_user_level_progress_area_id')
        batch_op.drop_index('ix_user_level_progress_level_id')
        batch_op.drop_index('ix_user_level_progress_user_id')
        batch_op.drop_constraint('user_level_progress_area_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])
        batch_op.drop_column('passed')
        batch_op.drop_column('area_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_level_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('passed', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_level_progress_area_id_fkey', 'areas', ['area_id'], ['id'])
        batch_op.create_index('ix_user_level_progress_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_user_level_progress_level_id', ['level_id'], unique=False)
        batch_op.create_index('ix_user_level_progress_area_id', ['area_id'], unique=False)
        batch_op.drop_column('best_score')
        batch_op.drop_column('attempts')
        batch_op.drop_column('status')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
