"""Add designations table and foreign key to users

Revision ID: 027ec460a0f0
Revises: 82dbb9c8214a
Create Date: 2024-10-30 01:19:24.182950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027ec460a0f0'
down_revision = '82dbb9c8214a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('designations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designation_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'designations', ['designation_id'], ['id'])
        batch_op.drop_column('designation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designation', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('designation_id')

    op.drop_table('designations')
    # ### end Alembic commands ###
