"""Make task_documents.task_id ON DELETE CASCADE

Revision ID: 21efa8a72730
Revises: f7cc5a308806
Create Date: 2025-06-01 15:57:55.518790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21efa8a72730'
down_revision = 'f7cc5a308806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_documents', schema=None) as batch_op:
        batch_op.drop_constraint('task_documents_task_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tasks', ['task_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('task_documents_task_id_fkey', 'tasks', ['task_id'], ['id'])

    # ### end Alembic commands ###
