"""Remove FK constraint from exam_access_requests.exam_id

Revision ID: 2db65cb3b722
Revises: 67b29cf68cf7
Create Date: 2025-05-19 14:52:20.266317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db65cb3b722'
down_revision = '67b29cf68cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_access_requests', schema=None) as batch_op:
        batch_op.drop_constraint('exam_access_requests_exam_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_access_requests', schema=None) as batch_op:
        batch_op.create_foreign_key('exam_access_requests_exam_id_fkey', 'exams', ['exam_id'], ['id'])

    # ### end Alembic commands ###
