"""Faillogin

Revision ID: 348518716fd0
Revises: d740eaaeba05
Create Date: 2025-05-07 03:39:54.841805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '348518716fd0'
down_revision = 'd740eaaeba05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('failed_login')
    # ### end Alembic commands ###
