"""Make is_verified non-nullable default false

Revision ID: 36e812d3a8b9
Revises: 0516901f940c
Create Date: 2025-08-04 13:15:31.513059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e812d3a8b9'
down_revision = '0516901f940c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_users_is_verified'), ['is_verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_privacy_agreed'), ['privacy_agreed'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_privacy_agreed_at'), ['privacy_agreed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_privacy_agreed_at'))
        batch_op.drop_index(batch_op.f('ix_users_privacy_agreed'))
        batch_op.drop_index(batch_op.f('ix_users_is_verified'))
        batch_op.alter_column('is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
