"""adding min level

Revision ID: 372e4c83126f
Revises: e7655ffa3a3b
Create Date: 2025-02-25 03:23:27.922079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372e4c83126f'
down_revision = 'e7655ffa3a3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minimum_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('minimum_designation_level', sa.Integer(), nullable=True))

    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minimum_level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.drop_column('minimum_level')

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_column('minimum_designation_level')
        batch_op.drop_column('minimum_level')

    # ### end Alembic commands ###
