"""Add StudyMaterial and StudyMaterialProgress models

Revision ID: 3c3a9577fc35
Revises: 1542b11e25f3
Create Date: 2024-12-30 02:09:47.489113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c3a9577fc35'
down_revision = '1542b11e25f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('standard_time', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('transcript_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_material_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('time_spent', sa.Integer(), nullable=True),
    sa.Column('completion_percentage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['study_materials.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_material_progress')
    op.drop_table('study_materials')
    # ### end Alembic commands ###
