"""Updated LevelArea and Category Models

Revision ID: 404d39ac6320
Revises: 9e4b6e53ba6a
Create Date: 2025-02-25 02:13:07.327684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404d39ac6320'
down_revision = '9e4b6e53ba6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('level_areas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('level_areas_area_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])
        batch_op.drop_column('area_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('level_areas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('level_areas_area_id_fkey', 'areas', ['area_id'], ['id'])
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
