"""Add user_task_association table for Task-User many-to-many relationship

Revision ID: 53dc429e1221
Revises: 1f7c6c2dbd74
Create Date: 2024-11-09 11:22:26.637793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53dc429e1221'
down_revision = '1f7c6c2dbd74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_task_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'task_id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('tasks_assigned_to_fkey', type_='foreignkey')
        batch_op.drop_column('assigned_to')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('tasks_assigned_to_fkey', 'users', ['assigned_to'], ['id'])

    op.drop_table('user_task_association')
    # ### end Alembic commands ###
