"""Increase verification & reset token column sizes

Revision ID: 5d1546d690e4
Revises: 91f8e74253f4
Create Date: 2025-05-15 14:04:16.543859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d1546d690e4'
down_revision = '91f8e74253f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('verification_token',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('password_reset_token',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_constraint('users_password_reset_token_key', type_='unique')
        batch_op.drop_constraint('users_verification_token_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('users_verification_token_key', ['verification_token'])
        batch_op.create_unique_constraint('users_password_reset_token_key', ['password_reset_token'])
        batch_op.alter_column('password_reset_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
        batch_op.alter_column('verification_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)

    # ### end Alembic commands ###
