"""add deleted_at to users

Revision ID: 647b1dbd6861
Revises: a83338cb876f
Create Date: 2025-05-15 13:25:27.992889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647b1dbd6861'
down_revision = 'a83338cb876f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
