"""Updated Level, Exam, and UserScore Models for Designation-Based Skipping

Revision ID: 6792e5070c22
Revises: 29f533c66855
Create Date: 2025-02-24 16:20:30.664590

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6792e5070c22'
down_revision = '29f533c66855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_level_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_level_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_level_progress_area_id'), ['area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_level_progress_level_id'), ['level_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_level_progress_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))

    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_id', sa.Integer(), nullable=True))
        batch_op.alter_column('files',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.PickleType(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'levels', ['level_id'], ['id'])

    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('level_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_progress_level_id'), ['level_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_progress_study_material_id'), ['study_material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_progress_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'levels', ['level_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_progress_study_material_id'))
        batch_op.drop_index(batch_op.f('ix_user_progress_level_id'))
        batch_op.drop_column('level_id')
        batch_op.drop_column('completed')

    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('files',
               existing_type=sa.PickleType(),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
        batch_op.drop_column('level_id')

    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.drop_column('title')

    with op.batch_alter_table('user_level_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_level_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_level_progress_level_id'))
        batch_op.drop_index(batch_op.f('ix_user_level_progress_area_id'))

    op.drop_table('user_level_progress')
    # ### end Alembic commands ###
