"""Add paper1_attempts & paper2

Revision ID: 6b603de654f1
Revises: c33fa135652d
Create Date: 2025-05-20 01:58:26.108053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b603de654f1'
down_revision = 'c33fa135652d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('special_exam_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paper1_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('paper2_attempts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('special_exam_records', schema=None) as batch_op:
        batch_op.drop_column('paper2_attempts')
        batch_op.drop_column('paper1_attempts')

    # ### end Alembic commands ###
