"""Updated Client ID

Revision ID: 70acf550b505
Revises: f6c21c855145
Create Date: 2025-03-27 15:27:21.661584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70acf550b505'
down_revision = 'f6c21c855145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_clients',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'client_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_client_id_fkey', type_='foreignkey')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('users_client_id_fkey', 'clients', ['client_id'], ['id'])

    op.drop_table('user_clients')
    # ### end Alembic commands ###
