"""Update studyMaterial Model

Revision ID: 79b8bf5fd298
Revises: a016f4cff9e7
Create Date: 2024-12-31 13:09:41.698838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b8bf5fd298'
down_revision = 'a016f4cff9e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('transcript_id', sa.String(length=255), nullable=True))
        batch_op.drop_column('transcript_url')
        batch_op.drop_column('video_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('transcript_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('transcript_id')
        batch_op.drop_column('video_id')

    # ### end Alembic commands ###
