"""Added fields for 2FA and password reset to User model

Revision ID: 82dbb9c8214a
Revises: ffc6b3de1f06
Create Date: 2024-10-29 23:53:18.860371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82dbb9c8214a'
down_revision = 'ffc6b3de1f06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_fa_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('two_fa_expiration', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('password_reset_expiration', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['password_reset_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password_reset_expiration')
        batch_op.drop_column('password_reset_token')
        batch_op.drop_column('two_fa_expiration')
        batch_op.drop_column('two_fa_code')

    # ### end Alembic commands ###
