"""Add video_id and transcript_id to StudyMaterial

Revision ID: 89f45cbc6ad1
Revises: e862105ba384
Create Date: 2025-01-07 17:42:54.647439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f45cbc6ad1'
down_revision = 'e862105ba384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('transcript_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.drop_column('transcript_id')
        batch_op.drop_column('video_id')

    # ### end Alembic commands ###
