"""enable ON DELETE CASCADE/SET NULL for all user FKs

Revision ID: 91f8e74253f4
Revises: 647b1dbd6861
Create Date: 2025-05-15 13:47:49.960469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91f8e74253f4'
down_revision = '647b1dbd6861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint('events_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_constraint('exams_created_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('special_exam_records', schema=None) as batch_op:
        batch_op.drop_constraint('special_exam_records_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('tasks_assigned_by_fkey', type_='foreignkey')
        batch_op.drop_constraint('tasks_completed_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['completed_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['assigned_by'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_clients', schema=None) as batch_op:
        batch_op.drop_constraint('user_clients_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_level_progress', schema=None) as batch_op:
        batch_op.drop_constraint('user_level_progress_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.drop_constraint('user_progress_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint('user_roles_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_scores', schema=None) as batch_op:
        batch_op.drop_constraint('user_scores_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_task_association', schema=None) as batch_op:
        batch_op.drop_constraint('user_task_association_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_task_association', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_task_association_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('user_scores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_scores_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_roles_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_progress_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('user_level_progress', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_level_progress_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('user_clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_clients_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tasks_completed_by_fkey', 'users', ['completed_by'], ['id'])
        batch_op.create_foreign_key('tasks_assigned_by_fkey', 'users', ['assigned_by'], ['id'])

    with op.batch_alter_table('special_exam_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('special_exam_records_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exams_created_by_fkey', 'users', ['created_by'], ['id'])

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('events_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
