"""Add max_time to StudyMaterial and start_time to StudyMaterialProgress

Revision ID: a016f4cff9e7
Revises: 3c3a9577fc35
Create Date: 2024-12-30 16:02:46.419174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a016f4cff9e7'
down_revision = '3c3a9577fc35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_material_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))

    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.drop_column('max_time')

    with op.batch_alter_table('study_material_progress', schema=None) as batch_op:
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
