"""Add IncorrectAnswer Table

Revision ID: a206b9292c3f
Revises: 2db65cb3b722
Create Date: 2025-05-19 23:35:46.602666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a206b9292c3f'
down_revision = '2db65cb3b722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incorrect_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('special_paper', sa.String(length=10), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incorrect_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incorrect_answers_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incorrect_answers_special_paper'), ['special_paper'], unique=False)
        batch_op.create_index(batch_op.f('ix_incorrect_answers_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_user_exam', ['user_id', 'exam_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incorrect_answers', schema=None) as batch_op:
        batch_op.drop_index('ix_user_exam')
        batch_op.drop_index(batch_op.f('ix_incorrect_answers_user_id'))
        batch_op.drop_index(batch_op.f('ix_incorrect_answers_special_paper'))
        batch_op.drop_index(batch_op.f('ix_incorrect_answers_exam_id'))

    op.drop_table('incorrect_answers')
    # ### end Alembic commands ###
