"""Add time_spent to UserProgress

Revision ID: a72f1a80a402
Revises: 0a0d73d2fe3e
Create Date: 2025-01-26 18:59:07.826606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a72f1a80a402'
down_revision = '0a0d73d2fe3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_spent', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.drop_column('time_spent')

    # ### end Alembic commands ###
