"""Add Module control Table

Revision ID: a83338cb876f
Revises: e7fbf7fdce71
Create Date: 2025-05-09 13:36:07.717109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a83338cb876f'
down_revision = 'e7fbf7fdce71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('module_roles',
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('module_id', 'role_id')
    )
    with op.batch_alter_table('special_exam_records', schema=None) as batch_op:
        batch_op.drop_column('paper2_attempts')
        batch_op.drop_column('paper1_attempts')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('special_exam_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paper1_attempts', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('paper2_attempts', sa.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('module_roles')
    op.drop_table('modules')
    # ### end Alembic commands ###
