"""removed the description column from area level

Revision ID: adbeca55ca36
Revises: 372e4c83126f
Create Date: 2025-02-25 11:15:23.190119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adbeca55ca36'
down_revision = '372e4c83126f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
