"""DB update for Study

Revision ID: b6f3f2726c23
Revises: da01f56997b8
Create Date: 2025-06-07 18:33:59.098254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f3f2726c23'
down_revision = 'da01f56997b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.drop_constraint('study_materials_minimum_level_fkey', type_='foreignkey')
        batch_op.drop_column('restriction_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restriction_level', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('study_materials_minimum_level_fkey', 'designations', ['minimum_level'], ['id'])

    # ### end Alembic commands ###
