"""Add phone_number and departments to users

Revision ID: ba8fe0837585
Revises: 76b52bd703b6
Create Date: 2024-12-01 14:55:00.324488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba8fe0837585'
down_revision = '76b52bd703b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('departments', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('departments')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
