"""Fixed relationships for Exam model

Revision ID: bc43c8aec50e
Revises: 0252a628666f
Create Date: 2025-02-25 02:25:58.280399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc43c8aec50e'
down_revision = '0252a628666f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
