"""Add foreign key to minimum_level in StudyMaterial

Revision ID: bcbc49cf99bf
Revises: ee1f79ace658
Create Date: 2025-02-26 17:05:50.274780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcbc49cf99bf'
down_revision = 'ee1f79ace658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'designations', ['minimum_level'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
