"""Add restriction_level to StudyMaterial

Revision ID: c298e373b51c
Revises: 91e66ff485f8
Create Date: 2025-01-13 01:38:25.004442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c298e373b51c'
down_revision = '91e66ff485f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restriction_level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.drop_column('restriction_level')

    # ### end Alembic commands ###
