"""Add used flag to ExamAccessRequest

Revision ID: c33fa135652d
Revises: a206b9292c3f
Create Date: 2025-05-20 01:09:54.075073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c33fa135652d'
down_revision = 'a206b9292c3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_access_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_access_requests', schema=None) as batch_op:
        batch_op.drop_column('used')

    # ### end Alembic commands ###
