"""Add admin_response column to support_tickets

Revision ID: da01f56997b8
Revises: 93d982b1bdb5
Create Date: 2025-06-03 18:30:59.384539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da01f56997b8'
down_revision = '93d982b1bdb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_response', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.drop_column('admin_response')

    # ### end Alembic commands ###
