"""initial

Revision ID: dbf738be692a
Revises: 7d338d99d155
Create Date: 2025-05-26 16:09:47.673518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf738be692a'
down_revision = '7d338d99d155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
