"""Add paper1_attempts and paper2_attempts to SpecialExamRecord

Revision ID: e7fbf7fdce71
Revises: d573697c998f
Create Date: 2025-05-07 15:12:10.265708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7fbf7fdce71'
down_revision = 'd573697c998f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('special_exam_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paper1_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('paper2_attempts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('special_exam_records', schema=None) as batch_op:
        batch_op.drop_column('paper2_attempts')
        batch_op.drop_column('paper1_attempts')

    # ### end Alembic commands ###
