"""Add chunks to StudyMaterial

Revision ID: e862105ba384
Revises: 79b8bf5fd298
Create Date: 2025-01-07 17:22:07.831968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e862105ba384'
down_revision = '79b8bf5fd298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_chunk_ids', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('transcript_chunk_ids', sa.Text(), nullable=True))
        batch_op.drop_column('video_id')
        batch_op.drop_column('transcript_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transcript_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('video_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('transcript_chunk_ids')
        batch_op.drop_column('video_chunk_ids')

    # ### end Alembic commands ###
