"""Add default value to minimum_level in StudyMaterial

Revision ID: ee1f79ace658
Revises: 313949cef8de
Create Date: 2025-02-26 16:55:57.757058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee1f79ace658'
down_revision = '313949cef8de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.alter_column('minimum_level',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('study_materials_minimum_level_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.create_foreign_key('study_materials_minimum_level_fkey', 'designations', ['minimum_level'], ['id'])
        batch_op.alter_column('minimum_level',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
