"""Add special_exam_records table

Revision ID: f6c21c855145
Revises: ecc55de5f036
Create Date: 2025-03-24 11:15:47.621399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6c21c855145'
down_revision = 'ecc55de5f036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('special_exam_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('paper1_score', sa.Float(), nullable=True),
    sa.Column('paper1_passed', sa.Boolean(), nullable=True),
    sa.Column('paper1_time_spent', sa.Integer(), nullable=True),
    sa.Column('paper1_completed_at', sa.DateTime(), nullable=True),
    sa.Column('paper2_score', sa.Float(), nullable=True),
    sa.Column('paper2_passed', sa.Boolean(), nullable=True),
    sa.Column('paper2_time_spent', sa.Integer(), nullable=True),
    sa.Column('paper2_completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('special_exam_records')
    # ### end Alembic commands ###
