"""Increase TaskDocument.filetype length to 255

Revision ID: f7cc5a308806
Revises: d011f7620353
Create Date: 2025-06-01 01:15:19.790541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7cc5a308806'
down_revision = 'd011f7620353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_documents', schema=None) as batch_op:
        batch_op.alter_column('filetype',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_documents', schema=None) as batch_op:
        batch_op.alter_column('filetype',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
