"""Add Role model and user_roles relationship to User

Revision ID: f86f446a9eaf
Revises: 67138a9b25ff
Create Date: 2025-04-08 15:32:52.382706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f86f446a9eaf'
down_revision = '67138a9b25ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('user_clients')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])
        batch_op.drop_column('departments')
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=50), server_default=sa.text("'member'::character varying"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('departments', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('department_id')

    op.create_table('user_clients',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='user_clients_client_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_clients_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'client_id', name='user_clients_pkey')
    )
    op.drop_table('departments')
    # ### end Alembic commands ###
